src/business/urls.py
from django.urls import path
from .views import dashboard, campaign_create, campaign_detail

app_name = 'business'

urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('create/', campaign_create, name='create'),
    path('detail/', campaign_detail, name='detail'),
]

src/influencer/urls.py
from django.urls import path
from .views import profile, task_list, dashboard

app_name = 'influencer'

urlpatterns = [
    path('profile/', profile, name='profile'),
    path('task_list/', task_list, name='task_list'),
    path('dashboard/', dashboard, name='dashboard'),
]

src/mememarketing/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

from public.views import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('influencer/', include('influencer.urls')),
    path('business/', include('business.urls')),
    path('accounts/', include('user.urls')),
    path('memer/', include('memer.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/memer/urls.py
from django.urls import path
from .views import task_list, detail, dashboard

app_name = 'memer'

urlpatterns = [
    path('task_list/', task_list, name='task_list'),
    path('detail/', detail, name='detail'),
    path('dashboard/', dashboard, name='dashboard'),
]

src/static_root/influencer/urls.py
from django.urls import path
from .views import (test_view,
    campaign_list,
    profile_create,
    influencers_assignment,
    campaign_detail,
    memer_assignment, 
    memer_detail,
    memer_dashboard,
    influencer_dashboard,
    login_view,
    register_view,
)

app_name = 'influencer'

urlpatterns = [
    path('test/', test_view, name='create-campaign'),
    path('list/', campaign_list, name='campaign-list'),
    path('profile/', profile_create, name='create-profile'),
    path('task_list/', influencers_assignment, name='assignments-list'), 
    path('detail/', campaign_detail, name='campaign-detail'),
    path('memer/', memer_assignment, name='memer-list'),
    path('memer/detail', memer_detail, name='memer-detail'),
    path('memer_dashboard/', memer_dashboard, name="memer-dashboard"),
    path('influencer_dashboard/', influencer_dashboard, name="influencer-dashboard"),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
]

src/static_root/mememarketing/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('influencer/', include('influencer.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/user/urls.py
from django.urls import path
from .views import profile_create, login, register

app_name = 'user'

urlpatterns = [
    path('profile_create/', profile_create, name='profile_create'),
    path('login/', login, name='login'),
    path('register/', register, name='register'),
]

src/business/models.py
from django.db import models

# Create your models here.

src/memer/models.py
from django.db import models

# Create your models here.

src/user/models.py
from django.db import models

# Create your models here.

src/business/views.py
from django.shortcuts import render


def dashboard(request):
    return render(request, 'business/dashboard.html', {})


def campaign_create(request):
    return render(request, 'business/campaign_create.html', {})


def campaign_detail(request):
    return render(request, 'business/campaign_detail.html', {})

src/influencer/views.py
from django.shortcuts import render


def profile(request):
    return render(request, 'influencer/profile.html', {})


def task_list(request):
    return render(request, 'influencer/assignment_list.html', {})


def dashboard(request):
    return render(request, 'influencer/dashboard.html', {})

src/memer/views.py
from django.shortcuts import render


def task_list(request):
    return render(request, 'memer/list.html', {})


def detail(request):
    return render(request, 'memer/detail.html', {})
    

def dashboard(request):
    return render(request, 'memer/dashboard.html', {})

src/static_root/influencer/views.py
from django.shortcuts import render


def test_view(request):
    return render(request, 'business/campaign_create.html', {})


def campaign_list(request):
    return render(request, 'business/campaign_list.html', {})


def profile_create(request):
    return render(request, 'user/profile_create.html', {})


def influencers_assignment(request):
    return render(request, 'influencer/assignment_list.html', {})


def campaign_detail(request):
    return render(request, 'business/campaign_detail.html', {})


def memer_assignment(request):
    return render(request, 'memer/list.html', {})


def memer_detail(request):
    return render(request, 'memer/detail.html', {})
    

def memer_dashboard(request):
    return render(request, 'memer/dashboard.html', {})


def influencer_dashboard(request):
    return render(request, 'influencer/dashboard.html', {})


def login_view(request):
    return render(request, 'user/login.html', {})


def register_view(request):
    return render(request, 'user/register.html', {})

    

src/user/views.py
from django.shortcuts import render


def profile_create(request):
    return render(request, 'user/profile_create.html', {})


def login(request):
    return render(request, 'user/login.html', {})


def register(request):
    return render(request, 'user/register.html', {})

    

src/static_root/templates/asset/bread.html
<div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        

src/static_root/templates/asset/card_stats.html
<div class="row">
    <div class="col-xl-3 col-md-6">
      <div class="card card-stats">
        <!-- Card body -->
        <div class="card-body">
          <div class="row">
            <div class="col">
              <h5 class="card-title text-uppercase text-muted mb-0">Total traffic</h5>
              <span class="h2 font-weight-bold mb-0">350,897</span>
            </div>
            <div class="col-auto">
              <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                <i class="ni ni-active-40"></i>
              </div>
            </div>
          </div>
          <p class="mt-3 mb-0 text-sm">
            <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
            <span class="text-nowrap">Since last month</span>
          </p>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-md-6">
      <div class="card card-stats">
        <!-- Card body -->
        <div class="card-body">
          <div class="row">
            <div class="col">
              <h5 class="card-title text-uppercase text-muted mb-0">New users</h5>
              <span class="h2 font-weight-bold mb-0">2,356</span>
            </div>
            <div class="col-auto">
              <div class="icon icon-shape bg-gradient-orange text-white rounded-circle shadow">
                <i class="ni ni-chart-pie-35"></i>
              </div>
            </div>
          </div>
          <p class="mt-3 mb-0 text-sm">
            <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
            <span class="text-nowrap">Since last month</span>
          </p>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-md-6">
      <div class="card card-stats">
        <!-- Card body -->
        <div class="card-body">
          <div class="row">
            <div class="col">
              <h5 class="card-title text-uppercase text-muted mb-0">Sales</h5>
              <span class="h2 font-weight-bold mb-0">924</span>
            </div>
            <div class="col-auto">
              <div class="icon icon-shape bg-gradient-green text-white rounded-circle shadow">
                <i class="ni ni-money-coins"></i>
              </div>
            </div>
          </div>
          <p class="mt-3 mb-0 text-sm">
            <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
            <span class="text-nowrap">Since last month</span>
          </p>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-md-6">
      <div class="card card-stats">
        <!-- Card body -->
        <div class="card-body">
          <div class="row">
            <div class="col">
              <h5 class="card-title text-uppercase text-muted mb-0">Performance</h5>
              <span class="h2 font-weight-bold mb-0">49,65%</span>
            </div>
            <div class="col-auto">
              <div class="icon icon-shape bg-gradient-info text-white rounded-circle shadow">
                <i class="ni ni-chart-bar-32"></i>
              </div>
            </div>
          </div>
          <p class="mt-3 mb-0 text-sm">
            <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
            <span class="text-nowrap">Since last month</span>
          </p>
        </div>
      </div>
    </div>
  </div>

src/static_root/templates/asset/footer.html
<footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-6">
        <div class="copyright text-center  text-lg-left  text-muted">
          &copy; 2020 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
        </div>
      </div>
      <div class="col-lg-6">
        <ul class="nav nav-footer justify-content-center justify-content-lg-end">
          <li class="nav-item">
            <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>
          </li>
          <li class="nav-item">
            <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
          </li>
          <li class="nav-item">
            <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
          </li>
          <li class="nav-item">
            <a href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>
          </li>
        </ul>
      </div>
    </div>
  </footer>

src/static_root/templates/asset/head.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
    <meta name="author" content="Creative Tim">
    <title>Argon Dashboard - Free Dashboard for Bootstrap 4</title>
    <!-- Favicon -->
    <link rel="icon" href="{% static 'img/brand/favicon.png' %}" type="image/png">
    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <!-- Icons -->
    <link rel="stylesheet" href="{% static 'vendor/nucleo/css/nucleo.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" type="text/css">
    <!-- Page plugins -->
    <!-- Argon CSS -->
    <link rel="stylesheet" href="{% static 'css/argon.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" type="text/css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">
    {% block stylesheets %}
    {% endblock %}
  </head>

src/static_root/templates/asset/scripts.html
{% load static %}

<!-- Argon Scripts -->
  <!-- Core -->
  {% block scripts %}
  {% endblock scripts %}
  <script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/js-cookie/js.cookie.js' %}"></script>
  <script src="{% static 'vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
  <script src="{% static 'vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}"></script>
  <!-- Optional JS -->
  <script src="{% static 'vendor/chart.js/dist/Chart.min.js' %}"></script>
  <script src="{% static 'vendor/chart.js/dist/Chart.extension.js' %}"></script>
  <!-- Argon JS -->
  <script src="{% static 'js/argon.js' %}"></script>

src/static_root/templates/asset/side.html
  {% load static %}
  <style>
    .sidenav-header
{
    height: 100px;

    text-align: center;
}
  </style>

  <!-- Sidenav -->
  <nav class="sidenav navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
      <!-- Brand -->
      <div class="sidenav-header align-items-center">
        <a class="navbar-brand" href="javascript:void(0)">
          <img src="{% static 'img/brand/meme-marketing transparent logo.png' %}" style="max-height:80px; height:80; padding-bottom:10%;" alt="...">
        </a>
      </div>
      <div class="navbar-inner">
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
          <!-- Nav items -->
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" href="#">
                <i class="ni ni-tv-2 text-primary"></i>
                <span class="nav-link-text">Dashboard</span>
              </a>
            </li>
            <li class="nav-item hover-effect">
              <a class="nav-link" href="{% url 'influencer:create-campaign' %}">
                <i class="ni ni-button-play text-primary"></i>
                <span class="nav-link-text">Create Campaign</span>
              </a>
            </li>
            <li class="nav-item hover-effect">
              <a class="nav-link" href="{% url 'influencer:campaign-list' %}">
                <i class="ni ni-bullet-list-67 text-primary"></i>
                <span class="nav-link-text">Campaigns List (Business)</span>
              </a>
            </li>
            <li class="nav-item hover-effect">
              <a class="nav-link" href="{% url 'influencer:create-profile' %}">
                <i class="ni ni-badge text-primary"></i>
                <span class="nav-link-text">Create Profile</span>
              </a>
            </li>
            <li class="nav-item hover-effect">
              <a class="nav-link" href="{% url 'influencer:assignments-list' %}">
                <i class="ni ni-bullet-list-67 text-primary"></i>
                <span class="nav-link-text">Campaigns List (Influencer)</span>
              </a>
            </li>
            <li class="nav-item hover-effect">
              <a class="nav-link" href="{% url 'influencer:campaign-detail' %}">
                <i class="ni ni-bullet-list-67 text-primary"></i>
                <span class="nav-link-text">Campaigns Detail (Business)</span>
              </a>
            </li>
            <li class="nav-item hover-effect">
              <a class="nav-link" href="{% url 'influencer:memer-list' %}">
                <i class="ni ni-bullet-list-67 text-primary"></i>
                <span class="nav-link-text">Campaigns List (Memer)</span>
              </a>
            </li>
            <li class="nav-item hover-effect">
              <a class="nav-link" href="{% url 'influencer:memer-detail' %}">
                <i class="ni ni-bullet-list-67 text-primary"></i>
                <span class="nav-link-text">memer-detail</span>
              </a>
            </li>
            <li class="nav-item hover-effect">
              <a class="nav-link" href="{% url 'influencer:memer-dashboard' %}">
                <i class="ni ni-bullet-list-67 text-primary"></i>
                <span class="nav-link-text">memer-dashboard</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>

src/static_root/templates/asset/top.html
{% load static %}

    <!-- Topnav -->
    <nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <h6 class="h2 text-white d-inline-block mb-0">Default</h6>
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark mt-2">
                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="#">Dashboards</a></li>
                <li class="breadcrumb-item active" aria-current="page">Default</li>
              </ol>
            </nav>
            <!-- Navbar links -->
            <ul class="navbar-nav align-items-center  ml-md-auto ">
              <li class="nav-item d-xl-none">
                <!-- Sidenav toggler -->
                <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
                  <div class="sidenav-toggler-inner">
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                  </div>
                </div>
              </li>
              <li class="nav-item d-sm-none">
                <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                  <i class="ni ni-zoom-split-in"></i>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="ni ni-bell-55"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-xl  dropdown-menu-right  py-0 overflow-hidden">
                  <!-- Dropdown header -->
                  <div class="px-3 py-3">
                    <h6 class="text-sm text-muted m-0">You have <strong class="text-primary">13</strong> notifications.</h6>
                  </div>
                  <!-- Notifications -->
                  <div class="list-group list-group-flush">
                    <a href="#!" class="list-group-item list-group-item-action">
                      <div class="row align-items-center">
                        <div class="col-auto">
                          <!-- Avatar -->
                          <img alt="Image placeholder" src="{% static '/img/theme/team-1.jpg' %}" class="avatar rounded-circle">
                        </div>
                        <div class="col ml--2">
                          <div class="d-flex justify-content-between align-items-center">
                            <div>
                              <h4 class="mb-0 text-sm">John Snow</h4>
                            </div>
                            <div class="text-right text-muted">
                              <small>2 hrs ago</small>
                            </div>
                          </div>
                          <p class="text-sm mb-0">Let's meet at Starbucks at 11:30. Wdyt?</p>
                        </div>
                      </div>
                    </a>
                  </div>
                  <!-- View all -->
                  <a href="#!" class="dropdown-item text-center text-primary font-weight-bold py-3">View all</a>
                </div>
              </li>

            </ul>
            <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
              <li class="nav-item dropdown">
                <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <div class="media align-items-center">
                    <span class="avatar avatar-sm rounded-circle">
                      <img alt="Image placeholder" src="{% static 'img/theme/team-4.jpg' %}">
                    </span>
                    <div class="media-body  ml-2  d-none d-lg-block">
                      <span class="mb-0 text-sm  font-weight-bold">John Snow</span>
                    </div>
                  </div>
                </a>
                <div class="dropdown-menu  dropdown-menu-right ">
                  <div class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Welcome!</h6>
                  </div>
                  <a href="#!" class="dropdown-item">
                    <i class="ni ni-single-02"></i>
                    <span>My profile</span>
                  </a>
                  <a href="#!" class="dropdown-item">
                    <i class="ni ni-settings-gear-65"></i>
                    <span>Settings</span>
                  </a>
                  <a href="#!" class="dropdown-item">
                    <i class="ni ni-calendar-grid-58"></i>
                    <span>Activity</span>
                  </a>
                  <a href="#!" class="dropdown-item">
                    <i class="ni ni-support-16"></i>
                    <span>Support</span>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#!" class="dropdown-item">
                    <i class="ni ni-user-run"></i>
                    <span>Logout</span>
                  </a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>

src/templates/asset/bread.html
<div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        

src/templates/asset/footer.html
<footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-4">
        <div class="copyright text-center  text-lg-left  text-muted">
          &copy; Meme Marketing 2020!
        </div>
      </div>
      <div class="col-lg-4">
        <div class="copyright text-center text-muted">
          Powered by
          <a href="http://fluffcoding.com">
            Fluff Coding
          </a>
        </div>
      </div>
      <div class="col-lg-4">
        <ul class="nav nav-footer justify-content-center justify-content-lg-end">
          <li class="nav-item">
            <a href="/how" class="nav-link" target="_blank">How it works</a>
          </li>
          </li>
        </ul>
      </div>
    </div>
  </footer>

src/templates/asset/side.html
  {% load static %}
  <style>
    .sidenav-header
{
    height: 100px;

    text-align: center;
}

  </style>

  <!-- Sidenav -->
  <nav class="sidenav navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
      <!-- Brand -->
      <div class="sidenav-header align-items-center">
        <a class="navbar-brand" href="javascript:void(0)">
          <img src="{% static 'img/brand/meme-marketing transparent logo.png' %}" style="max-height:80px; height:80; padding-bottom:10%;" alt="...">
        </a>
      </div>
      <div class="navbar-inner">
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
          <!-- Nav items -->
          <!-- Divider -->
        <!-- Heading -->
        <h6 class="navbar-heading text-muted mt-3" style="margin:0; padding:0;">Business</h6>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link " href="{% url 'business:dashboard' %}">
                <i class="ni ni-tv-2 text-primary"></i>
                <span class="nav-link-text">Dashboard</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'business:create' %}">
                <i class="ni ni-tv-2 text-primary"></i>
                <span class="nav-link-text">Create Campaign</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'business:detail' %}">
                <i class="ni ni-tv-2 text-primary"></i>
                <span class="nav-link-text">Campaign Detail</span>
              </a>
            </li>
          </ul>
        <h6 class="navbar-heading text-muted mt-3" style="margin:0; padding:0;">Memer</h6>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link " href="{% url 'memer:task_list' %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Task List</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'memer:detail' %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Campaign Detail</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'memer:dashboard' %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Dashboard</span>
            </a>
          </li>
        </ul>
        <h6 class="navbar-heading text-muted mt-3" style="margin:0; padding:0;">Influencer</h6>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link " href="{% url 'influencer:profile' %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Profile</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'influencer:task_list' %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Task List</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'influencer:dashboard' %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Dashboard</span>
            </a>
          </li>
        </ul>
        <h6 class="navbar-heading text-muted mt-3" style="margin:0; padding:0;">Accounts</h6>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link " href="{% url 'user:profile_create' %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Create Profile</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:login' %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Login</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:register' %}">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Register</span>
            </a>
          </li>
        </ul>
        </div>
      </div>
    </div>
  </nav>

src/templates/staticpages_asset/header.html
{% load static %}

<nav id="navbar-main" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand" href="#">
        <img src="{% static 'img/brand/white.png' %}">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse navbar-custom-collapse collapse" id="navbar-collapse">
        <div class="navbar-collapse-header">
          <div class="row">
            <div class="col-6 collapse-brand">
              <a href="dashboard.html">
                <img src="{% static 'img/brand/meme-marketing transparent logo.png' %}">
              </a>
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a href="#" class="nav-link">
              <span class="nav-link-inner--text">How it works</span>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <span class="nav-link-inner--text">Dashboard</span>
            </a>
          </li>
        </ul>
        <hr class="d-lg-none" />
        <ul class="navbar-nav align-items-lg-center ml-lg-auto">
          <li class="nav-item">
            <a class="nav-link nav-link-icon" href="https://www.facebook.com/mememarketingpk" target="_blank" data-toggle="tooltip" data-original-title="Like us on Facebook">
              <i class="fab fa-facebook-square"></i>
              <span class="nav-link-inner--text d-lg-none">Facebook</span>
            </a>
          </li>
          <li class="nav-item d-none d-lg-block ml-lg-4">
            <a href="{% url 'user:register' %}" class="btn btn-neutral btn-icon">
              <span class="btn-inner--icon">
                <i class="fas fa-laugh-squint mr-2"></i>
              </span>
              <span class="nav-link-inner--text">Join Now!</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
    <!-- Main content -->
    <div class="main-content">
        <!-- Header -->
        <div class="header bg-gradient-primary py-7 py-lg-8 pt-lg-9">
    
          <div class="separator separator-bottom separator-skew zindex-100">
            <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
              <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
            </svg>
          </div>
        </div>